[package]
name = "votestv"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
argh = "0.1.7"
csv = "1.1"
tallystick = { version = "0.4.3", features = ["nightly"] }
